version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html  # Apache web directory
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
